# Generated by Django 5.1.1 on 2026-02-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_group', models.CharField(default='EVIAN', max_length=100)),
                ('material_description', models.CharField(max_length=255)),
                ('pack_size_old', models.CharField(max_length=50)),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('base_unit', models.CharField(max_length=50)),
                ('order_unit', models.CharField(max_length=50)),
                ('sales_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('material_number', models.CharField(max_length=50)),
                ('qty_in_pallet', models.IntegerField()),
                ('qty_in_layers', models.IntegerField()),
                ('qty_layers', models.IntegerField()),
                ('image_3d', models.ImageField(upload_to='products/')),
                ('image_bird', models.ImageField(upload_to='products/')),
                ('image_carton', models.ImageField(upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
